### ISSUE TITLE
在2台ecs服务器上面的问题

### ISSUE THREAD

**Issue by YukiYlf** [648540858/wvp-GB28181#4]
在腾讯云1台SIP
在阿里云1流媒体
发现始终不能返回

hook_api在流媒体是正确的
正在测试中

**Comment by 648540858** [comment]
ok, 我测试下回复你

**Comment by tsinemperor** [comment]
碰到类似的问题，分析原因在于，腾讯云和阿里云服务器基于docker的镜像虚拟服务器，配置sip时候用的是虚拟服务器的IP，而不是公网IP，那么流媒体服务和国标\IPC等通信的时候会有走内网IP的情况，国标本身可以NAT穿透，但是流媒体暂时没发现怎么穿透（或者不好穿透？），我现在的解决办法是让流媒体和国标属于同一个公网环境网络。您也可以试试NAT穿透配置。

**Comment by 648540858** [comment]
公网部署支持已添加,可以测试了
