### ISSUE TITLE
能否实现提取预置位并调用预置位，能在项目中直接设置预置位那是最好，还有就是能否实现喊话功能。

### ISSUE THREAD

**Issue by 818ajian** [648540858/wvp-GB28181#5]
感谢您不断更新和努力！能否实现提取预置位并调用预置位，能在项目中直接设置预置位那是最好，还有就是能否实现喊话功能。

**Comment by 648540858** [comment]
预置位命令我只查到设置, 调用,删除,不知道否满足使用
语音对讲暂时还没实现方案

**Comment by 818ajian** [comment]
感谢回复，能实现您说的功能也是不错，丰富了应用，国标很大问题不能实时获取PTZ值及移动到指定绝对位。

**Comment by 648540858** [comment]
#9 完善前端控制信令，实现GB28181 A.3前端设备控制协议
感谢 @lawrencehj 提供的代码,你可以测试下,我先关闭了
