### ISSUE TITLE
请问Maven的打包命令是什么?

### ISSUE THREAD

**Issue by Liuzizai** [648540858/wvp-GB28181#7]
使用Maven package 打包无法正常运行

**Comment by Liuzizai** [comment]
建议更改jain-sip-ri包的maven依赖

**Comment by Liuzizai** [comment]
<dependency>
			<groupId>javax.sip</groupId>
			<artifactId>jain-sip-ri</artifactId>
			<version>1.3.0-91</version>
		</dependency>

**Comment by lawrencehj** [comment]
https://www.cnblogs.com/dreamowneryong/p/7307908.html
