### ISSUE TITLE
执行streamByeCmd(ssrc)方法无法让摄像头停止推流

### ISSUE THREAD

**Issue by Liuzizai** [648540858/wvp-GB28181#8]
zlm的流注销成功,但是摄像头未停止往指定端口推流,tcpdump -i eth0 port 30000 仍可看到摄像头再往30000端口推流

**Comment by 648540858** [comment]
抓包看下byte消息是否正常

**Comment by Liuzizai** [comment]
问题已解决。端口默认使用了设备端的sip端口，应改为设备注册时的ip和端口
